<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Table Names
    |--------------------------------------------------------------------------
    |
    | If you would like to customise the names of the tables that will be
    | generated by the migrations, you can alter the table names here
    |
    */

    // Table for the Lnch\LaravelBouncer\Permission model
    'permissions_table_name' => 'permissions',

    // Junction table between permissions and other models
    'permissions_junction_table_name' => 'permissions_models',

];
